### ISSUE TITLE
How to train your code in multi gpu?

### ISSUE THREAD

**Issue by Wallace-222** [facebookresearch/DomainBed#10]
I wonder how to add the nn.DataParallel in your code to train on multi gpus.

Thanks a lot.

**Comment by lopezpaz** [comment]
Can you try adding
```python
algorithm = torch.nn.DataParallel(algorithm, device_ids=range(torch.cuda.device_count()))
```
after [this line](https://github.com/facebookresearch/DomainBed/blob/master/domainbed/scripts/train.py#L130)? Learn more about DataParallel [here](https://pytorch.org/docs/master/generated/torch.nn.DataParallel.html).

**Comment by SirRob1997** [comment]
This doesn't work for me, runs into the following error message:

`torch.nn.modules.module.ModuleAttributeError: 'DataParallel' object has no attribute 'update'`

**Comment by igul222** [comment]
I think you have the right idea re. subclassing `DataParallel`. My understanding is that `DistributedDataParallel` requires a special launcher utility so it'll be harder to integrate with the sweep code.

**Comment by lopezpaz** [comment]
Please comment in this issue if multi-gpu training is a priority in your workflow.

**Comment by shuangliumax** [comment]
> Please comment if multi-gpu training is a priority in your workflow, so I will re-open this issue.
Hello, because my hardware is limited, there is not enough memory to test on the domainnet dataset, so parallel multi-GPU training is required, but it cannot be done according to the code you provided and my own modifications

**Comment by kowshikthopalli** [comment]
Yes. It will be nice to reopen this and enable this. I would like to work on Transformers and most of them dont fit in a single GPU

**Comment by novelyear** [comment]
> Please comment if multi-gpu training is a priority in your workflow, so I will re-open this issue.

Hello, this is a nice work, it's so helpful. But I need to train in a huge dataset, so multi-GPU training is necessary. I try to use DataParallel, but I have been haunted by it for 2 days and haven't worked out it. Please reopen this issue🥲
