### ISSUE TITLE
Issue in using InfiniteDataLoader with Lightning

### ISSUE THREAD

**Issue by jivatneet** [facebookresearch/DomainBed#113]
I'm trying to use `InfiniteDataLoader` in `lib.fast_data_loader` with the Pytorch Lightning Module
```
train_loaders = [InfiniteDataLoader(
    dataset=env,
    weights=env_weights,
    batch_size=batch_size,
    num_workers=dataset.N_WORKERS)
    for i, (env, env_weights) in enumerate(in_splits)
    if i not in test_envs + val_envs]
    
trainer.fit(algorithm, train_loaders)
```

The training loop goes on forever in this case. If I add a `__len__` function similar to `FastDataLoader` in `InfiniteDataLoader` class, the problem is solved. However, I wanted to ask if this would cause issues with the expected behaviour of the `InfiniteDataLoader`.

**Comment by lopezpaz** [comment]
I don't see any issues, but we do not support Lightning.
