### ISSUE TITLE
Error "Object of type int64 is not JSON serializable"

### ISSUE THREAD

**Issue by ZouXinn** [facebookresearch/DomainBed#115]
When I run train.py with the MLDG algorithm, an error saying that "Object of type int64 is not JSON serializable" occurs. At line 
     File "/home/zx/DomainBed/domainbed/scripts/train.py", line 257, in <module>
         f.write(json.dumps(results, sort_keys=True) + "\n")

After debugging I find it comes from the "_hparam('n_meta_test', 2, lambda r:  r.choice([1, 2]))" line in the hparams_registry file. It is because that r.choice returns a numpy.int64 type data, which may lead to an error sometimes. I think we should change it to "_hparam('n_meta_test', 2, lambda r:  int(r.choice([1, 2])))" to transfer the selected number to the int type

**Comment by lopezpaz** [comment]
Mind sending a pull request?

**Comment by noparkee** [comment]
Hello!
Recently, this error occurred to me, too.
Are you fixing this error now? Just like ZouXinn said, it works!
