### ISSUE TITLE
Question about the results

### ISSUE THREAD

**Issue by Cheungki** [facebookresearch/DomainBed#116]
Hi, thanks for your great work!

I'm wondering that are those results released on your paper coming from the script [sweep.py](https://github.com/facebookresearch/DomainBed/blob/main/domainbed/scripts/sweep.py)?

Another question is that, for example, when we train a model for PACS using DomainBed with env0 as the test_env, should we use the highest result in env0_in_acc or just the last one or anything else?

Thanks.

**Comment by lopezpaz** [comment]
Please use `collect_results.py` to produce tables. The results of the sweep are mentioned in other closed issues.
