### ISSUE TITLE
MyLauncher for SLURM

### ISSUE THREAD

**Issue by Spandan-Madan** [facebookresearch/DomainBed#123]
I'd like to launch a sweep on a SLURM based cluster. Can someone please advise what the MyLauncher function should look like?

Thanks!

**Comment by jc-audet** [comment]
I have something for that! #56 (Disclaimer: Use at own risk. It might not be appropriate for you cluster, but the general structure is there)

**Comment by lopezpaz** [comment]
Take a look at `submitit`, too.
