### ISSUE TITLE
Where are unlabelled data used in DANN?

### ISSUE THREAD

**Issue by Deathn0t** [facebookresearch/DomainBed#131]
First thank you for this really nice collection of implementations for domain adaptation 😄 and with a really clean code!

I was wondering if it is normal if the `unlabeled` parameter is not used in the `update` function of the `DANN` algorithm. More specifically the `update` code is [here](https://github.com/facebookresearch/DomainBed/blob/main/domainbed/algorithms.py#L247) and if I understand it right the call to `update` is in the `training.py` script [here](https://github.com/facebookresearch/DomainBed/blob/main/domainbed/scripts/train.py#L216) where it looks like the `uda_device` data are the unlabelled data passed to the `update` function as the second parameter so corresponding to the `unlabeled`.

So, my current understanding of the code is that the "target domain" is not being used (when it should). If my understanding is good I can try fixing this and submit a PR to the repository.

**Comment by abalhomaid** [comment]
would love to have an example code of an algorithm that uses `unlabled`. From what I see, `unlabled` isn't used in any algorithm

**Comment by piotr-teterwak** [comment]
Hi, as noticed, the code base has scaffolding for domain adaptation but it is not yet enabled for any algorithm. If anybody would like to enable this, feel free to submit a PR. Closing for now.
