### ISSUE TITLE
Add Adaptiope Dataset

### ISSUE THREAD

**Issue by iamharsha1999** [facebookresearch/DomainBed#134]
Hi, 

Thanks for the framework first of all. Very recently I came across the adaptiope dataset which seems like a new benchmark. Can you add this ? 

Link to paper: https://openaccess.thecvf.com/content/WACV2021/papers/Ringwald_Adaptiope_A_Modern_Benchmark_for_Unsupervised_Domain_Adaptation_WACV_2021_paper.pdf

**Comment by piotr-teterwak** [comment]
Hi @iamharsha1999, this repository is not under active development. However if you'd like to add this dataset feel free to submit a PR, and we will take a look.
