### ISSUE TITLE
cannot download the terra incognita dataset

### ISSUE THREAD

**Issue by zhyhan** [facebookresearch/DomainBed#136]
Thanks for the great effort in domain generalization. Now, I cannot download the terra incognita dataset even using the newest source at https://[lilablobssc.blob.core.windows.net/caltechcameratraps/eccv_18_all_images_sm.tar.gz](https://lilablobssc.blob.core.windows.net/caltechcameratraps/eccv_18_all_images_sm.tar.gz).

**Comment by bugwriterLee** [comment]
I have encountered the same issue; have you resolved it yet?

**Comment by piotr-teterwak** [comment]
Hi @bugwriterLee , looking into it.

**Comment by piotr-teterwak** [comment]
https://lila.science/datasets/caltech-camera-traps

It seems like it is here, under "CCT20 Benchmark subset". I will edit the download script when I get a moment.

**Comment by bugwriterLee** [comment]
Thanks!

**Comment by piotr-teterwak** [comment]
Fixed in 3cf2e20fb885f3ecf2e97b83268bb6c896568075. Feel free to re-open if there are further issues.
