### ISSUE TITLE
please provide a standard format to train custom dataset on domainbed

### ISSUE THREAD

**Issue by welcome-to-my-webpage** [facebookresearch/DomainBed#137]

**Comment by piotr-teterwak** [comment]
@welcome-to-my-webpage ; closing for now due to inactivity and lack of detailed issue description. Feel free to re-open with more detail.

**Comment by RohitSingh1226** [comment]
In my case, I have a dataset with 35 classes equally distributed over 4-5 domains, I would like to know the exact procedure to test the algorithms provided with my data and get the results in the table specified. 

In the paper, there was a lot of emphasis over the model selection, if I already have an efficient net model pre-trained on the ImageNet1k would the procedure differ?
