### ISSUE TITLE
Jobs for leaveone-out model selection

### ISSUE THREAD

**Issue by AmirEstiri** [facebookresearch/DomainBed#138]
Hi,
Thanks for the library. In cases where a job includes multiple test environments e.g. `test_envs: [0,1]`, which method selection uses the results of these jobs? From what I understood, only training and oracle use them. Is that correct?

**Comment by piotr-teterwak** [comment]
Hi @AmirEstiri , currently none of the model selection methods are compatible with multiple test environments. You can see in https://github.com/facebookresearch/DomainBed/blob/main/domainbed/model_selection.py#L6, that all records are filtered to only have a single test env.
