### ISSUE TITLE
DANN Gradient Reversal Layer Missing

### ISSUE THREAD

**Issue by st862** [facebookresearch/DomainBed#143]
I am interested in the DANN model by Ganin. In the paper, they use a Gradient Reversal Layer(GRL)  to reach the saddle point using single SGD updates. I don't see any mention of GRL in this repository so interested in how you implemented DANN.

**Comment by Bogay** [comment]
I think the implementation uses a hparam `lambda` for this, which defaults to 1. In this case, the expression becomes `classifier_loss - disc_loss`, which has the same behavior as GRL.

https://github.com/facebookresearch/DomainBed/blob/93ebb6bccdb46d40471ce0713a165aaf7b5e21b6/domainbed/algorithms.py#L287-L288

**Comment by piotr-teterwak** [comment]
@Bogay is correct, closing. Feel free to re-open if there are further questions.
