### ISSUE TITLE
如何对Camelyon17的处理

### ISSUE THREAD

**Issue by yuu-Wang** [facebookresearch/DomainBed#153]
看到您datasets.py里面对Camelyon17的处理代码：
class WILDSCamelyon(WILDSDataset):
    ENVIRONMENTS = [ "hospital_0", "hospital_1", "hospital_2", "hospital_3",
            "hospital_4"]
    def __init__(self, root, test_envs, hparams):
        dataset = Camelyon17Dataset(root_dir=root)
        super().__init__(
            dataset, "hospital", test_envs, hparams['data_augmentation'], hparams)
我下载下来的Camelyon17的数据集没有hospital_0", "hospital_1", "hospital_2", "hospital_3",
            "hospital_4"，是要运行datasets.py来对之进行划分吗

**Comment by piotr-teterwak** [comment]
Hi @yuu-Wang , is this a duplicate of https://github.com/facebookresearch/DomainBed/issues/151?

**Comment by yuu-Wang** [comment]
> 看到您datasets.py里面对Camelyon17的处理代码： class WILDSCamelyon(WILDSDataset): ENVIRONMENTS = [ "hospital_0", "hospital_1", "hospital_2", "hospital_3", "hospital_4"] def **init**(self, root, test_envs, hparams): dataset = Camelyon17Dataset(root_dir=root) super().**init**( dataset, "hospital", test_envs, hparams['data_augmentation'], hparams) 我下载下来的Camelyon17的数据集没有hospital_0", "hospital_1", "hospital_2", "hospital_3", "hospital_4"，是要运行datasets.py来对之进行划分吗
