### ISSUE TITLE
Guarantee that sampled hyperparameters are the same for future commits

### ISSUE THREAD

**Issue by SirRob1997** [facebookresearch/DomainBed#16]
Just opening this here to keep track of the issue mentioned in #12:

"We will have to find a solution to guarantee that the same random parameters are sampled in `hparams_registry` given the same random seed, for all future commits. Right now, adding algorithms or conditional logic in `hparams_registry` changes the random hyperparameters sampled for a given algorithm, dataset, and seed."

**Comment by igul222** [comment]
Took a shot at fixing this. Let me know if you have thoughts.

**Comment by SirRob1997** [comment]
Once this has been fixed it is probably a good idea to run a new sweep. From that point onwards adding a new algorithm should only require running that particular algorithm on all datasets

**Comment by FlayQQQ** [comment]
After 5 years I see this 🥴🫶
