### ISSUE TITLE
Saving and loading trained models 

### ISSUE THREAD

**Issue by eyeris** [facebookresearch/DomainBed#21]
Hi I was wondering how to save amodel and then use it later. Turned out that each training instance saves 'model.pkl' in to the directory and have 'algorithm.module' only. Is there a way to save the model and use it later as an standalone module. I am moving from Keras to Pytorch so kind of new to the functionalities. Appreciate an answer for this.

**Comment by lopezpaz** [comment]
```python
import torch
from domainbed import algorithms

def load_model(fname):
    dump = torch.load(fname)
    algorithm_class = algorithms.get_algorithm_class(dump["args"]["algorithm"])
    algorithm = algorithm_class(
        dump["model_input_shape"],
        dump["model_num_classes"],
        dump["model_num_domains"],
        dump["model_hparams"])
    algorithm.load_state_dict(dump["model_dict"])
    return algorithm

model = load_model("model.pkl")
```
