### ISSUE TITLE
About MLDG's update()

### ISSUE THREAD

**Issue by Genie-Kim** [facebookresearch/DomainBed#27]
This was written in the MLDG's update function.
"TODO: update() has at least one bug, possibly more. Disabling this whole algorithm until it gets figured out."
Maybe this bug is about second-order derivatives?
If not, please explain what kind of problem this bug is about.

**Comment by lopezpaz** [comment]
We fixed a couple of bugs in MLDG in the past, and we forgot to remove this comment. Thank you.
