### ISSUE TITLE
Could you share the selected hyperparameters to reproduce the results?

### ISSUE THREAD

**Issue by khanrc** [facebookresearch/DomainBed#32]
Hi, thanks to your great work.

I'm trying to reproduce the results reported in the paper. For the ERM, the default hyperparameter setting yields similar results as reported in the PACS, but it shows a little worse in the VLCS than reported. I suspect the difference come from the hyperparamters, so I wonder the searched values. Could you share the selected hyperparameters, at least for the ERM?

**Comment by lopezpaz** [comment]
See: https://github.com/facebookresearch/DomainBed/blob/master/domainbed/scripts/list_top_hparams.py

**Comment by khanrc** [comment]
@lopezpaz Thanks to fast answer. I know the script, but there is no log file in this repo and I have no resource to search hparams myself. Do you have no plan to share the search results, for people who lack resource like me?

**Comment by lopezpaz** [comment]
@khanrc Here you go all the logs from the last public sweep: https://drive.google.com/file/d/16VFQWTble6-nB5AdXBtQpQFwjEC7CChM/view?usp=sharing

**Comment by khanrc** [comment]
Thanks a lot! :)

**Comment by kowshikthopalli** [comment]
Do you also by any chance stored the checkpoints at the end of each run.? That would be really helpful. 

Thanks
