### ISSUE TITLE
Multi-GPU Launcher

### ISSUE THREAD

**Issue by Luodian** [facebookresearch/DomainBed#34]
It's a very excellent repo!  Thanks for building it.

But I am wondering if there's a way to add a multi-GPU launcher to "command_launchers.py" for more convenient use.

For E.g. If I have an 8-GPUs machine, and I want to launch 8 jobs every time for the 8 GPU.

Is there a way to do it? or some ideas that I would then contribute some efforts to build one.

**Comment by Luodian** [comment]
I modified these lines in "sweep.py", from line 80 to line 99. I am not sure if this would be appropriate. If so, would I be able to create a PR?
```
        all_gpu_counts = torch.cuda.device_count()
        commands_per_gpu = {}
        for i in range(all_gpu_counts):
            commands_per_gpu[i] = []

        idx = 0
        while idx < len(commands):
            for i in range(all_gpu_counts):
                if idx < len(commands):
                    commands_per_gpu[i].append("CUDA_VISIBLE_DEVICES={} {}".format(i, commands[idx]))
                    idx += 1

        multi_gpus_processes = []
        for i in range(all_gpu_counts):
            p = Process(target=launcher_fn, args=(commands_per_gpu[i],))
            p.start()
            multi_gpus_processes.append(p)

        for p in multi_gpus_processes:
            p.join()

**Comment by igul222** [comment]
Hi, thanks for the interest in contributing! I think this is a good idea. A cleaner way to implement this would be as a command launcher in command_launchers.py. Just write a function that runs each command in a list, and add the function to the registry at the bottom of the file. You can use your command launcher by running sweep.py with the --command_launcher flag.

**Comment by igul222** [comment]
I've gone ahead and taken a first shot at an implementation at https://github.com/facebookresearch/DomainBed/commit/56196cc5f8a8d53d3d7f547e385c443cbcb73dcd . Hope this helps!

**Comment by lopezpaz** [comment]
Thank you @igul222. Please re-open if necessary, @Luodian.
