### ISSUE TITLE
Different results in the README page and the paper

### ISSUE THREAD

**Issue by shiliang26** [facebookresearch/DomainBed#38]
Hi,

I may have missed something, but it seems what's reported in the "Current results" section in the README page is different from Table 4 in the original paper. I wonder has it been updated, and how?

Thank you!

**Comment by lopezpaz** [comment]
The last version of the paper is the one accepted in ICLR 2021 (https://openreview.net/forum?id=lQdXeXDoWtI), uses commit 7df6f06, and matches the results from the README.md file.

**Comment by shiliang26** [comment]
Thanks for responding so quickly! You might wanna update the link in the README file though.

**Comment by kowshikthopalli** [comment]
sorry to open this again. There is quite a discrepancy in the results reported in arxiv version and the open review version atleast for VLCS and other datasets. Just to be clear, I will have to compare my results with openreview version itself correct?

**Comment by lopezpaz** [comment]
Openreview version for now, it is the latest. Thanks.
