### ISSUE TITLE
Predefined groups for training groupDRO

### ISSUE THREAD

**Issue by pavanteja295** [facebookresearch/DomainBed#39]
Hello,
Thank you very much for this amazing comparison. I have slight confusion regarding the implementation of groupDRO. 
In the [groupDRO](https://arxiv.org/abs/1911.08731) paper authors carefully generate the training datasets to contain a mixture of groups that are defined by leveraging human knowledge (identify some spurious correlations).

However, in this repository and comparison in the paper I fail to see such a construction of predefined groups for groupDRO. As far as I understand the [implementation,](https://github.com/facebookresearch/DomainBed/blob/master/domainbed/algorithms.py) dataset is **randomly** sampled and each sample in the minibatch is considered to arrive from one particular training group.  I understand that predefining groups on a new dataset is difficult but is it justifiable to compare groupDRO with such a relaxation. I tried to look into the paper associated with this repo, however, I did not see any mention on the same.  

Thank you so much for your time and patience!

**Comment by lopezpaz** [comment]
This repository deals with domain generalization problems. That is, algorithms receive minibatches = ((X1, Y1), ..., (XG, YG)), where (Xg, Yg) is a minibatch of labeled examples from domain (group) g, for all g = 1, ..., G.
