### ISSUE TITLE
About reproduced RSC result in DomainBed

### ISSUE THREAD

**Issue by junyoo96** [facebookresearch/DomainBed#40]
Hi, I want to know about RSC results(reproduced on DomainBed) experimented on datasets(PACS,OfficeHome,VLCS) in DomainBed. I can't find specific results of RSC(results for each domain) in your paper.
If you can, could you show me results like this form?
     A              C             P               S
88.1±0.1  77.9±1.3  97.8±0.0  79.1±0.9

Here are what I want to know!

PACS

   
1. Average accuracy of each domain (ResNet18 with RSC)
   
2. Average accuracy of each domain (ResNet50 with RSC)
   

OfficeHome

   
3. Average accuracy of each domain (ResNet18 with RSC)

4. Average accuracy of each domain (ResNet50 with RSC)   

VLCS

   
5. Average accuracy of each domain (ResNet18 with RSC)     

6 .Average accuracy of each domain (ResNet50 with RSC)

**Comment by lopezpaz** [comment]
For ResNet50 results, see Appendix C in https://openreview.net/pdf?id=lQdXeXDoWtI

We only have ablation studies (e.g., experiments with ResNet18) for ERM.
