### ISSUE TITLE
About algorithm MMD

### ISSUE THREAD

**Issue by AllenPu** [facebookresearch/DomainBed#44]
I'm wondering if you really implement the "Domain Generalization with Adversarial Feature Learning" the MMD algorithm?
Since it seems no adversarial autoencode in the code?

**Comment by lopezpaz** [comment]
That's correct, for us MMD only uses MMD. The alternative using an adversary is DANN. We will clarify.

**Comment by AllenPu** [comment]
> That's correct, for us MMD only uses MMD. The alternative using an adversary is DANN. We will clarify.

Got it! 
SO can I understand that the feature extraction is not so important in this paper, so you keep the MMD part (as I found that in the code AbstractMMD part)
