### ISSUE TITLE
Severe decrease in MMD performance on DomainNet dataset

### ISSUE THREAD

**Issue by MohammadJavadD** [facebookresearch/DomainBed#49]
It seems the CORAL and MMD algorithms are very similar, and based on the "current result" table, in most datasets, they achieve close results.  However,  there is a big difference in their accuracy on the DomainNet dataset (41.5-23.4). I was wondering, is there any specific reason for this, or might it be a bug?

**Comment by lopezpaz** [comment]
No known reason. Please re-open if you investigate further.
