### ISSUE TITLE
ERM results from a randomly initialized network.

### ISSUE THREAD

**Issue by vdevmcitylp** [facebookresearch/DomainBed#52]
The paper provides results for ERM using ResNet50 models initialized with ImageNet weights. Please let me know if there are results available for models trained from scratch as well.

It'll be interesting to see how much of an effect ImageNet weights have on the final results. Using an ImageNet initialization is in a way equivalent to indirectly using the entire ImageNet dataset for training. While this will not invalidate the claims in the paper as most DG methods use ImageNet weights as a starting point, training a model from scratch will give a fairer idea of the contribution of the ERM algorithm itself for DG.

**Comment by lopezpaz** [comment]
We do not provide such results (as we believe in any realistic setting pre-trained networks would be used), but shall you run them and find something interesting, please reopen this issue.
