### ISSUE TITLE
MLP with depth=1

### ISSUE THREAD

**Issue by cdancette** [facebookresearch/DomainBed#54]
Hi,
Thanks for this great library.
We encountered a minor issue: the MLP class does not support the case of depth=1. The minimum length for the MLP is 2 right now. It could be a nice addition to create linear layers.

**Comment by lopezpaz** [comment]
Hi! Linear classifiers can be used by setting `hparams['nonlinear_classifier'] = False`, as implemented [here](https://github.com/facebookresearch/DomainBed/blob/master/domainbed/networks.py#L207).
