### ISSUE TITLE
ColorMNIST domain error

### ISSUE THREAD

**Issue by WenWeiTHU** [facebookresearch/DomainBed#57]
In paper, the colormnist domain is {0.1, 0.3, 0.9}
![image](https://user-images.githubusercontent.com/39073236/124071134-7ee49000-da71-11eb-9524-b3f76386910b.png)

But in code, , the colormnist domain is {0.1, 0.2, 0.9}
![image](https://user-images.githubusercontent.com/39073236/124071203-97ed4100-da71-11eb-88c3-f17522cf22f5.png)

**Comment by lopezpaz** [comment]
The original IRM paper considers {0.1, 0.2, 0.9}.
