### ISSUE TITLE
Rotated-MNIST results

### ISSUE THREAD

**Issue by alexrame** [facebookresearch/DomainBed#65]
Would it be possible to provide the results for Rotated-MNIST for commit 7df6f06 with 2 digits precision?
Indeed, most methods are between 97.8 and 98.0 with the oracle model selection - complexifying the comparison.
Thank you in advance.

**Comment by lopezpaz** [comment]
Full sweep logs available at: https://drive.google.com/file/d/16VFQWTble6-nB5AdXBtQpQFwjEC7CChM/view?usp=sharing
