### ISSUE TITLE
Requirements up to date ?

### ISSUE THREAD

**Issue by jmamath** [facebookresearch/DomainBed#72]
I just cloned the repo and tried to run the train command. However I got the following error:
`AttributeError: module 'torchvision.transforms' has no attribute 'InterpolationMode'`

Is the requirements.txt file up to date ?
Here is my setting: 
```
Environment:
        Python: 3.8.5
        PyTorch: 1.7.1
        Torchvision: 0.8.2
        CUDA: 11.0
        CUDNN: 8004
        NumPy: 1.20.3
        PIL: 8.3.2
Args:
        algorithm: ERM
        checkpoint_freq: None
        data_dir: ./domainbed/data/MNIST/
        dataset: RotatedMNIST
        holdout_fraction: 0.2
        hparams: None
        hparams_seed: 0
        output_dir: train_output
        save_model_every_checkpoint: False
        seed: 0
        skip_model_save: False
        steps: None
        task: domain_generalization
        test_envs: [0]
        trial_seed: 0
        uda_holdout_fraction: 0
HParams:
        batch_size: 64
        class_balanced: False
        data_augmentation: True
        lr: 0.001
        nonlinear_classifier: False
        resnet18: False
        resnet_dropout: 0.0
        weight_decay: 0.0
```

**Comment by ashok-arjun** [comment]
Hi @jmamath, I was the one who created the `requirements.txt` file through [this PR](https://github.com/facebookresearch/DomainBed/pull/71/commits).

I put the requirements file after training only coloredMNIST; I just saw that R-MNIST has this command.

Feel free to correct the requirements file (I believe the torch version and torchvision version are tightly coupled, and they are also coupled with the CUDA version).

**Comment by lopezpaz** [comment]
Closing in favor of a PR (@ashok-arjun ?)
