### ISSUE TITLE
Extending Domainbed code for a new algorithm

### ISSUE THREAD

**Issue by maryam089** [facebookresearch/DomainBed#73]
Thank you so much for providing such good and efficient responses to all issues. 
In the supp material of the paper, it is mentioned that:
**Algorithms are classes that implement two methods: .update(minibatches) and
.predict(x). The update method receives a list of minibatches, one minibatch per training
domain, and each minibatch containing one input and one output tensor**
what is one input and output tensor ? and also if you can provide a bit more explanation on how to integrate a new model by inheriting the ERM, it would be helpful.

**Comment by lopezpaz** [comment]
Check for instance the mixup implementation at:

https://github.com/facebookresearch/DomainBed/blob/main/domainbed/algorithms.py#L406-L435

Or any other method from that file.
