### ISSUE TITLE
cannot access PACS dataset

### ISSUE THREAD

**Issue by zwvews** [facebookresearch/DomainBed#74]
I cannot download the PACS dataset and could you please have a check the provided download link?
https://drive.google.com/uc?id=0B6x7gtvErXgfbF9CSk53UkRxVzg

**Comment by lopezpaz** [comment]
I can access it, try again after deleting your gdown cache, namely `rm -rf ~/.cache/gdown/`

**Comment by lopezpaz** [comment]
Oh, I see; updated the link. Thanks @zwvews and @dali-dl.
