### ISSUE TITLE
Restrict the model selection criterion to just "train_domain_validation"

### ISSUE THREAD

**Issue by ukdsvl** [facebookresearch/DomainBed#77]
Hi,

It has been observed that there are a significantly large number of jobs that are being launched while running the sweep. Wanted to know how can we restrict the model selection criterion to just "train_domain_validation" (for eg)?

Can you please give the precise command if possible ?

**Comment by lopezpaz** [comment]
The sweep is a collection of jobs to be run. The model selection criteria is an strategy to pick models from a sweep. These are two independent processes. You can hack `sweep.py` to limit the amount of jobs to the ones you care about.
