### ISSUE TITLE
Would it be possible to run a new sweep?

### ISSUE THREAD

**Issue by cwognum** [facebookresearch/DomainBed#82]
The [last sweep](https://github.com/facebookresearch/DomainBed/blob/main/domainbed/results/2020_10_06_7df6f06/results.png) is from 14 months ago and since then 10 new algorithms have been added. These newly added algorithms generally present only partial or no results at all on DomainBed. To the best of my knowledge, [Fishr](https://arxiv.org/pdf/2109.02934.pdf) (Table 4) includes the most up-to-date sweep, but it still lacks 6 of the currently available algorithms.

I would be curious to get an updated overview of how the current set of algorithms compare to one another, but I personally do not have access to the compute to run such a sweep. Would it by any chance be possible for you to schedule a new sweep sometime soon?

**Comment by lopezpaz** [comment]
We are indeed planning it, but given the amount of compute, we are first considering some refactoring of the code. We will update the repository as soon as we have new results available.
