### ISSUE TITLE
About BN layer

### ISSUE THREAD

**Issue by DevinCheung** [facebookresearch/DomainBed#84]
https://github.com/facebookresearch/DomainBed/blob/fef79d51f5f15286b91e93615a058791a4825c71/domainbed/networks.py#L80

Hi, I noticed that the above line was commented out. I would like to consult in which of the following two settings are the results in the paper obtained?

(1) all BN layers in ResNet50 are removed
(2) all BN layers in ResNet50 are set to ".eval()", i.e. running mean/variance is fixed, weights and biases are trainable

**Comment by lopezpaz** [comment]
(2)
