### ISSUE TITLE
MLDG domain split bug

### ISSUE THREAD

**Issue by shakedpe** [facebookresearch/DomainBed#94]
In the update rule of the function "random_pairs_of_minibatches" which extract pairs for meta-train and meta-test, you use all possible pairs permutation before using optimizer.step. This is not as the formula defined in the paper where you need to split the domains to V meta test and S-V meta train, aggregate and do the optimization step, while domains are split.

**Comment by Dsyforever** [comment]
I also discover this problem, they mix up all the source domain data to calculate two objective. that's wrong.

**Comment by lopezpaz** [comment]
@shakedpe @Dsyforever mind sending fix?

**Comment by shakedpe** [comment]
Sure
I also enabled choosing how many meta test you want by adding a parameter to the function hparams_registery.
This is the function im using instead:

`

    def split_meta_train_test(minibatches, num_meta_test=1):
        n_domains = len(minibatches)
        perm = torch.randperm(n_domains).tolist()
        pairs = []
        meta_train = perm[:(n_domains-num_meta_test)]
        meta_test = perm[-num_meta_test:]

        for i,j in zip(meta_train, cycle(meta_test)):
             xi, yi = minibatches[i][0], minibatches[i][1]
             xj, yj = minibatches[j][0], minibatches[j][1]

             min_n = min(len(xi), len(xj))
             pairs.append(((xi[:min_n], yi[:min_n]), (xj[:min_n], yj[:min_n])))

        return pairs
`

**Comment by lopezpaz** [comment]
Fixed by #95
